#!/bin/sh

## This is certainly not a perfect test, but I hope to improve it in
## the future.
## (Actually I'm not going to extend this any further. See dotest
## instead.  
set -e

bras clean >/dev/null


bras >testoutput
diff -C 3 testoutput Test1/run1.out || exit 1

bras >testoutput
diff -C 3 testoutput Test1/run2.out || exit 1

rm testoutput
cd Test1
rm  cNewer cSuffixNewer.y cSuffixExist.s firstFile somefile
rm cExist cSuffixNewer.x cSuffixExist.r otherfile cNewerBad
