#!/bin/sh

## This is certainly not a perfect test, but I hope to improve it in
## the future.

set -e
trap 'rm testoutput' 0 15

bras clean >/dev/null


bras >testoutput
diff -C 3 testoutput Test1/run1.out || exit 1

bras >testoutput
diff -C 3 testoutput Test1/run2.out || exit 1
